### ISSUE TITLE
is it possible for you to release the retrain log file?

### ISSUE THREAD

**Issue by aptsunny** [Adlik/zen_nas#8]
hi, @lyg95 , In paper and official code, retrain the searched model by the feature loss cost too much resource, the 1.2ms latency model is very difficult to train completely end to end. so whether the series model‘s log can be released? 

<img width="640" alt="image" src="https://user-images.githubusercontent.com/36404164/163673713-1414717f-9106-4ee3-8ed1-43a0c21ca81f.png">

- latency12ms 83.6% or 83.466%

**Comment by lyg95** [comment]
Hi @aptsunny， I found that the training results are lost in the original log [searched_latency12ms_83.466_train_image_classification.log](https://github.com/Adlik/zen_nas/files/8503283/searched_latency12ms_83.466_train_image_classification.log).
I provide a similar model training log  for your reference [searched_latency12ms_train_image_classification.log](https://github.com/Adlik/zen_nas/files/8503251/searched_latency12ms_train_image_classification.log)
